import { Inter } from 'next/font/google';

import { AppProviders } from '@/client/appProviders/AppProviders';

import { AvailableLocale, availableLanguages } from '@/language';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function localeLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: AvailableLocale };
}) {
  const messages = availableLanguages[params.locale].lang;

  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <AppProviders locale={params.locale} messages={messages}>
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
